// helix: components/UseCases.tsx
/**
 * @helix:story USER-73000
 * @helix:story USER-303000
 *
 * UseCases — canonical landing-page use cases band showcasing
 * representative scenarios and quotes across the user types served
 * by Helix (developers, indie hackers, startups, enterprise teams,
 * researchers).
 *
 *   • Glass-card grid: role, headline, scenario, outcome, testimonial.
 *   • Pure server component, content lives in this module so it
 *     ships independently of any in-flight content/ refactors.
 *   • Section chrome (eyebrow / heading / lede) is rendered inline
 *     so the band is self-contained when imported directly.
 */
import * as React from "react";

import { Container } from "@/components/ui/Container";
import { cn } from "@/components/ui/cn";

type UseCaseId =
  | "developer"
  | "indie-hacker"
  | "startup"
  | "enterprise"
  | "researcher";

type Accent = "cyan" | "violet" | "fuchsia" | "amber" | "emerald";

interface UseCase {
  readonly id: UseCaseId;
  readonly role: string;
  readonly headline: string;
  readonly scenario: string;
  readonly outcome: string;
  readonly quote: string;
  readonly attribution: string;
  readonly accent: Accent;
}

const USE_CASES: ReadonlyArray<UseCase> = [
  {
    id: "developer",
    role: "Senior developers",
    headline: "Stop reviewing 2,000-line AI PRs.",
    scenario:
      "You're handed a sprawling diff generated by an AI agent and asked to review it before merge.",
    outcome:
      "Helix breaks the work into atomic units. Each unit is scoped, type-checked, tested, and linted — so your review is a fast yes/no, not a forensic audit.",
    quote:
      "Helix turned our AI coding agent into a teammate we can actually trust to merge code.",
    attribution: "Avery K., Staff Engineer — Series B Fintech",
    accent: "cyan",
  },
  {
    id: "indie-hacker",
    role: "Indie hackers",
    headline: "Ship a feature on a Tuesday night.",
    scenario:
      "You have a working app, a backlog of ideas, and no co-founder to share the load.",
    outcome:
      "Describe the next feature in a sentence. Helix plans the units, executes them, and hands you review-ready PRs by morning — so your side project keeps moving.",
    quote:
      "I shipped more in one weekend with Helix than in the last quarter without it.",
    attribution: "Jamie L., Indie Maker — Solo SaaS",
    accent: "violet",
  },
  {
    id: "startup",
    role: "Early-stage startups",
    headline: "Move fast without breaking main.",
    scenario:
      "Your seed-stage team is moving at sprint speed and main has been red more than green.",
    outcome:
      "Helix isolates every unit in its own worktree and gates merges on verification, so velocity goes up without reliability going down.",
    quote:
      "Main hasn't been red in three months. That's a first for us with AI agents.",
    attribution: "Marcus D., Founding Engineer — Dev Tools Startup",
    accent: "fuchsia",
  },
  {
    id: "enterprise",
    role: "Enterprise platform teams",
    headline: "Governance, by construction.",
    scenario:
      "You need to roll out AI-assisted coding across dozens of repos without losing audit trails or standards.",
    outcome:
      "Helix runs against your existing type-check, test, and lint pipelines — so every unit ships inside the guardrails your security team already trusts.",
    quote:
      "Helix is the first AI tool our security team approved without a six-month review.",
    attribution: "Priya N., Head of Product — B2B SaaS",
    accent: "emerald",
  },
  {
    id: "researcher",
    role: "Researchers & ML engineers",
    headline: "Prototype fast, evaluate rigorously.",
    scenario:
      "You want to compare multiple AI agents on the same task without manually wiring up scratch repos.",
    outcome:
      "Spin up Helix against any agent SDK, run the same prompt through atomic units, and compare the verified outputs side by side.",
    quote:
      "Helix gave us reproducible, auditable runs across every agent we benchmark.",
    attribution: "Dr. Hana T., ML Research Lead — Applied AI Lab",
    accent: "amber",
  },
];

const ACCENT_CLASSES: Readonly<Record<Accent, string>> = {
  cyan: "from-cyan-400/20 to-cyan-400/0 text-cyan-300 ring-cyan-400/30",
  violet: "from-violet-400/20 to-violet-400/0 text-violet-300 ring-violet-400/30",
  fuchsia:
    "from-fuchsia-400/20 to-fuchsia-400/0 text-fuchsia-300 ring-fuchsia-400/30",
  amber: "from-amber-400/20 to-amber-400/0 text-amber-300 ring-amber-400/30",
  emerald:
    "from-emerald-400/20 to-emerald-400/0 text-emerald-300 ring-emerald-400/30",
};

export interface UseCasesProps {
  className?: string;
}

export function UseCases({ className }: UseCasesProps): React.ReactElement {
  return (
    <section
      id="use-cases"
      aria-labelledby="use-cases-heading"
      className={cn("relative py-24 sm:py-32", className)}
    >
      {/* Subtle decorative backdrop */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 -z-10"
        style={{
          backgroundImage:
            "radial-gradient(700px 400px at 10% 0%, rgba(34,211,238,0.10), transparent 60%), radial-gradient(800px 400px at 100% 100%, rgba(139,92,246,0.10), transparent 60%)",
        }}
      />

      <Container>
        <div className="mx-auto max-w-2xl text-center">
          <span className="hx-chip mx-auto">
            <span className="hx-chip-dot" />
            Use cases
          </span>
          <h2
            id="use-cases-heading"
            className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-4xl"
          >
            Built for every way teams ship code with AI.
          </h2>
          <p className="mt-4 text-base leading-relaxed text-white/70 sm:text-lg">
            From a single developer chasing a side project to a platform
            team rolling out AI-assisted coding org-wide — Helix adapts to
            the shape of your team.
          </p>
        </div>

        <ul
          role="list"
          className="mt-16 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"
        >
          {USE_CASES.map((useCase) => {
            const accent = ACCENT_CLASSES[useCase.accent];
            return (
              <li
                key={useCase.id}
                className="group relative overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03] p-6 shadow-lg shadow-black/10 backdrop-blur transition hover:border-white/20 hover:bg-white/[0.05]"
              >
                {/* Accent gradient strip */}
                <div
                  aria-hidden="true"
                  className={cn(
                    "absolute inset-x-0 top-0 h-px bg-gradient-to-r",
                    accent,
                  )}
                />

                <div className="flex items-center justify-between">
                  <span
                    className={cn(
                      "inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium ring-1 ring-inset",
                      accent,
                    )}
                  >
                    {useCase.role}
                  </span>
                </div>

                <h3 className="mt-5 text-lg font-semibold text-white">
                  {useCase.headline}
                </h3>

                <div className="mt-4 space-y-3 text-sm leading-relaxed text-white/70">
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-wider text-white/50">
                      Scenario
                    </p>
                    <p className="mt-1">{useCase.scenario}</p>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-wider text-white/50">
                      Outcome
                    </p>
                    <p className="mt-1">{useCase.outcome}</p>
                  </div>
                </div>

                <figure className="mt-6 border-t border-white/10 pt-5">
                  <blockquote className="text-sm italic leading-relaxed text-white/80">
                    “{useCase.quote}”
                  </blockquote>
                  <figcaption className="mt-2 text-xs text-white/50">
                    — {useCase.attribution}
                  </figcaption>
                </figure>
              </li>
            );
          })}
        </ul>
      </Container>
    </section>
  );
}

export default UseCases;