// helix: components/UseCases.tsx
/**
 * @helix:story USER-73000
 * @helix:story USER-303000
 *
 * UseCases — canonical landing-page use cases band showcasing
 * representative scenarios and quotes across the user types served
 * by Helix (developers, indie hackers, startups, enterprise teams,
 * researchers).
 *
 *   • Glass-card grid: role, headline, scenario, outcome, testimonial.
 *   • Pure server component, content lives in this module so it
 *     ships independently of any in-flight content/ refactors.
 *   • Section chrome (eyebrow / heading / lede) is rendered inline
 *     so the band is self-contained when imported directly.
 */
import * as React from "react";

import { Container } from "@/components/ui/Container";
import { cn } from "@/components/ui/cn";

type UseCaseId =
  | "developer"
  | "indie-hacker"
  | "startup"
  | "enterprise"
  | "researcher";

type Accent = "cyan" | "violet" | "fuchsia" | "amber" | "emerald";

interface UseCase {
  readonly id: UseCaseId;
  readonly role: string;
  readonly headline: string;
  readonly scenario: string;
  readonly outcome: string;
  readonly quote: string;
  readonly attribution: string;
  readonly accent: Accent;
}

const USE_CASES: ReadonlyArray<UseCase> = [
  {
    id: "developer",
    role: "Senior developers",
    headline: "Stop reviewing 2,000-line AI PRs.",
    scenario:
      "You're handed a sprawling diff generated by an AI agent and asked to review it before merge.",
    outcome:
      "Helix breaks the work into atomic units. Each unit is scoped, type-checked, tested, and linted — so your review is a fast yes/no, not a forensic audit.",
    quote:
      "Helix turned our AI coding agent into a teammate we can actually trust to merge code.",
    attribution: "Avery K., Staff Engineer — Series B Fintech",
    accent: "cyan",
  },
  {
    id: "indie-hacker",
    role: "Indie hackers",
    headline: "Ship a feature on a Tuesday night.",
    scenario:
      "You have a working app, a backlog of ideas, and no co-founder to share the load.",
    outcome:
      "Describe the next feature in a sentence. Helix plans the units, executes them, and hands you review-ready PRs by morning — so your side project keeps moving.",
    quote:
      "I shipped more in one weekend with Helix than in the last quarter without it.",
    attribution: "Jamie L., Indie Maker — Solo SaaS",
    accent: "violet",
  },
  {
    id: "startup",
    role: "Early-stage startups",
    headline: "Move fast without breaking main.",
    scenario:
      "Your seed-stage team is moving at sprint speed and main has been red more than green.",
    outcome:
      "Helix isolates every unit in its own worktree and gates merges on verification, so velocity goes up without reliability going down.",
    quote:
      "Main hasn't been red in three months. That's a first for us with AI agents.",
    attribution: "Marcus D., Founding Engineer — Dev Tools Startup",
    accent: "fuchsia",
  },
  {
    id: "enterprise",
    role: "Enterprise platform teams",
    headline: "Governance, by construction.",
    scenario:
      "You need to roll out AI-assisted coding across dozens of repos without losing audit trails or standards.",
    outcome:
      "Helix runs against your existing type-check, test, and lint pipelines — so every unit ships inside the guardrails your security team already trusts.",
    quote:
      "Helix is the first AI tool our security team approved without a six-month review.",
    attribution: "Priya N., Head of Product — B2B SaaS",
    accent: "emerald",
  },
  {
    id: "researcher",
    role: "Researchers & ML engineers",
    headline: "Prototype fast, evaluate rigorously.",
    scenario:
      "You want to compare multiple AI agents on the same task without manually wiring up scratch repos.",
    outcome:
      "Spin up Helix against any agent SDK, run the same prompt through atomic units, and compare the verified outputs side by side.",
    quote:
      "Helix gave us reproducible, auditable runs across four agents in an afternoon.",
    attribution: "Dr. Hana O., Research Lead — Applied AI Lab",
    accent: "amber",
  },
];

const accentRing: Record<Accent, string> = {
  cyan: "before:bg-cyan-400/40",
  violet: "before:bg-violet-400/40",
  fuchsia: "before:bg-fuchsia-400/40",
  emerald: "before:bg-emerald-400/40",
  amber: "before:bg-amber-400/40",
};

const accentChip: Record<Accent, string> = {
  cyan: "bg-cyan-400/10 text-cyan-200 ring-cyan-400/30",
  violet: "bg-violet-400/10 text-violet-200 ring-violet-400/30",
  fuchsia: "bg-fuchsia-400/10 text-fuchsia-200 ring-fuchsia-400/30",
  emerald: "bg-emerald-400/10 text-emerald-200 ring-emerald-400/30",
  amber: "bg-amber-400/10 text-amber-200 ring-amber-400/30",
};

export interface UseCasesProps {
  className?: string;
}

export function UseCases({ className }: UseCasesProps): React.ReactElement {
  return (
    <section
      id="use-cases"
      aria-labelledby="use-cases-heading"
      className={cn(
        "relative isolate overflow-hidden border-y border-white/5 bg-white/[0.015] py-24 sm:py-32",
        className,
      )}
    >
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 -z-10"
        style={{
          backgroundImage:
            "radial-gradient(60% 50% at 20% 0%, rgba(34,211,238,0.10), transparent 60%), radial-gradient(50% 50% at 85% 10%, rgba(139,92,246,0.10), transparent 60%)",
        }}
      />
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 -z-10 opacity-40"
        style={{
          backgroundImage:
            "linear-gradient(rgba(255,255,255,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.04) 1px, transparent 1px)",
          backgroundSize: "56px 56px",
          maskImage:
            "radial-gradient(80% 60% at 50% 30%, black 0%, transparent 70%)",
          WebkitMaskImage:
            "radial-gradient(80% 60% at 50% 30%, black 0%, transparent 70%)",
        }}
      />

      <Container>
        <header className="mx-auto max-w-3xl text-center">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300/90 sm:text-sm">
            Use cases
          </p>
          <h2
            id="use-cases-heading"
            className="mt-3 text-balance text-3xl font-semibold tracking-tight sm:text-4xl md:text-5xl"
          >
            Built for every team shipping with AI.
          </h2>
          <p className="mt-4 text-pretty text-base text-white/70 sm:text-lg">
            From solo founders to platform teams, Helix turns one good prompt
            into a stack of atomic, reviewable pull requests.
          </p>
        </header>

        <ul
          role="list"
          className="mx-auto mt-12 grid w-full max-w-6xl grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"
        >
          {USE_CASES.map((uc) => (
            <li
              key={uc.id}
              className={cn(
                "group relative isolate overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03] p-6 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)] transition-colors hover:border-white/20 hover:bg-white/[0.05]",
                "before:absolute before:inset-x-0 before:top-0 before:h-px",
                accentRing[uc.accent],
              )}
            >
              <span
                className={cn(
                  "inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] ring-1 ring-inset",
                  accentChip[uc.accent],
                )}
              >
                {uc.role}
              </span>
              <h3 className="mt-4 text-lg font-semibold tracking-tight text-white">
                {uc.headline}
              </h3>
              <p className="mt-3 text-sm leading-relaxed text-white/65">
                <span className="font-semibold text-white/85">Scenario. </span>
                {uc.scenario}
              </p>
              <p className="mt-2 text-sm leading-relaxed text-white/65">
                <span className="font-semibold text-white/85">Outcome. </span>
                {uc.outcome}
              </p>

              <figure className="mt-5 border-t border-white/10 pt-4">
                <blockquote className="text-sm leading-relaxed text-white/80">
                  <span aria-hidden="true" className="select-none text-cyan-300/70">
                    &ldquo;
                  </span>
                  {uc.quote}
                  <span aria-hidden="true" className="select-none text-cyan-300/70">
                    &rdquo;
                  </span>
                </blockquote>
                <figcaption className="mt-2 text-xs text-white/55">
                  {uc.attribution}
                </figcaption>
              </figure>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  );
}

export default UseCases;